### ISSUE TITLE
External Auth/DB Support

### ISSUE THREAD

**Issue by jnovack** [alexyoung/ircd.js#57]
Rather than using the same ol' NickServ, I'd propose filling the hole that nickserv currently does not fill, external auth connections.

This would have to be fleshed out more, but some procedure of validating ext users and passwords (or session identifiers) with external databases.

USE CASE: 
Any website with a users table.  The nickserv would only allow connections (or only joins to +r rooms) from users who have validated against it.

Specifically, a forum website could ensure that everyone uses their forum names in the chat.  Therefore, using your favorite client (which we all know is irsii) or, for seemless integration, the webclient could send a session key to the client (which would be stored in the db).

I understand this is months away, just wanted to add that the future projects :)

**Comment by krazyjakee** [comment]
Sorry to bump but third party integrations would be awesome!

I understand this is not an ircd core issue but has anyone had any luck with this or know any modules to help out with this?

Thanks.

**Comment by ozjd** [comment]
I believe this a part of RFC1459. The user issues PASS before NICK.
You'd need to update a config file, and reload it on the server.

**Comment by jnovack** [comment]
Closed due to lack of interest.
