### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by dannysmc95** [alexyoung/ircd.js#92]
Hi there,

I am looking at building an IRC server or cluster of them using NodeJS; I have seen your version seems to be the most up-to-date and thought instead of starting from the beginning it might be worth just expanding yours?

Is it possible to be a contributor?

Thanks,
Danny

**Comment by AlMcKinlay** [comment]
Nudging this issue. I'm going to be doing some work over on McInkay/ircd.js and will contribute some PRs back, but it would be great to get this project moving a bit more.
